|**INFO-B211:**|ASSIGNMENT-5|
|-|-:|
|**STUDENT NAME:**|Jacob Letterman|


### Question-1: Classification Example (10 marks)

- Explore the pima Indian diabetes dataset available at:
- https://www.kaggle.com/uciml/pima-indians-diabetes-database

    - Get the shape of dataset and print the number of samples and the number columns in this dataset.
    - Get the number of features and their names. 
    - Get the shape of the target variable column.
    - Using scikit-learn, develop a machine learning classifier (support vector or k-nearest neighbors or random forest or decision tree classifiers) that can be fit on 80 % of this dataset for learning or training and predict the class of patient either diabetes or not on the remaining 20 % of this dataset.
    - Test the performance of your classifier by reporting about the its accuracy, precision, recall and F1-score.
    - Print the TP, TN, FP, FN measures from the confusion matrix of the classifier that you have developed.

### Question-2: Regression Example (10 marks)

- Explore the cpu-performance dataset available at:
- https://archive.ics.uci.edu/ml/datasets/Computer+Hardware

    - Get the shape of the dataset excluding the target variable column.
    - Get the number of samples in this dataset?
    - Get the number of features and their names. 
    - Get the shape of the target variable column.
    - using scikit-learn, develop a machine learning regression model (support vector for regression (SVR) or linear regression LR) that can be fit on 160 samples of this dataset for learning or training and predict the value of cpu-performance on the remaining samples of this dataset.
    - Test the performance of your regression model by reporting about the mean square error and the mean absolute error between the predicted and true values of the target variable for this dataset.

In [4]:
#Question 1
import numpy as np
import pandas as pd
import sklearn
raw_data = "C:/Users/cactu/Downloads/diabetes.csv"
dataset = pd.read_csv(raw_data, delimiter = ',')
print(dataset.shape)
#Number of samples
df = pd.DataFrame(dataset, index=None)
print(len(df))
#Number of columns
print(len(df.axes[1]))

(768, 9)
768
9


In [5]:
#Number of features and Names
print(len(df.axes[1]),'\n')
for col_names in df:
    print(col_names)

9 

Pregnancies
Glucose
BloodPressure
SkinThickness
Insulin
BMI
DiabetesPedigreeFunction
Age
Outcome


In [6]:
#Shape of target variable column
target = df.iloc[:,-1]
target.shape

(768,)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train,y_train)

NameError: name 'X_train' is not defined

In [15]:
#Machine Learning Classifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
X = df.drop(columns=['Outcome'])
y = df['Outcome'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1, stratify=y)
knn2 = KNeighborsClassifier()
param_grid = {'n_neighbors': np.arange(1, 25)}
knn_gscv = GridSearchCV(knn2, param_grid, cv=5)
print(knn_gscv.fit(X, y))
print(knn_gscv.best_params_)
print(knn_gscv.best_score_)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])})
{'n_neighbors': 14}
0.7578558696205755


In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

#Standardize the data set
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

#Fit the SVC model
svc = SVC(kernel='linear', C=10.0, random_state=1)
svc.fit(X_train, y_train)

#Get the predictions
y_pred = svc.predict(X_test)

#Calculate the confusion matrix
conf_matrix = confusion_matrix(y_true=y_test, y_pred=y_pred)
conf_matrix

array([[133,  17],
       [ 38,  43]], dtype=int64)

In [69]:
#Presicion
Precision_Score = TP / (FP + TP)
Precision_Score

0.75

In [71]:
#Accuracy
Accuracy_Score = (TP + TN)/ (TP + FN + TN + FP)
Accuracy_Score

0.625

In [70]:
#Recall
Recall_Score = TP / (FN + TP)
Recall_Score

0.6

In [73]:
#F-1 Score
F1_Score = 2* Precision_Score * Recall_Score/ (Precision_Score + Recall_Score)
F1_Score

0.6666666666666665

In [24]:
#Question 2
import numpy as np
import pandas as pd
raw_data = ("C:/Users/cactu/Downloads/machine.data")
x = pd.read_csv(raw_data, sep=',')
df = pd.DataFrame(x, index = None)
df.shape

(208, 10)

In [25]:
#Number of samples
length = len(df)
length

208

In [26]:
#Number of features and names
print(len(df.axes[1]),'\n')
for col in df.columns:
    print(col)

10 

adviser
32/60
125
256
6000
256.1
16
128
198
199


In [27]:
#Shape of target column
target = df.iloc[:,-1]
target.shape

(208,)

In [33]:
#Machine Learning Regression Model
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
X_l = df.iloc[:, 8:-1].values
y_p = df.iloc[:, -1].values

y_p = y_p.reshape(-1,1)

print(X_l)
print(y_p)

StdS_X = StandardScaler()
StdS_y = StandardScaler()

X_l = StdS_X.fit_transform(X_l)
y_p = StdS_y.fit_transform(y_p)
#Prediction of CPU performance
regressor = SVR(kernel = 'rbf')
regressor.fit(X_l, y_p)
A=regressor.predict(StdS_X.transform([[6.5]]))
print(A)
B_pred = StdS_y.inverse_transform(regressor.predict(StdS_X.transform([[6.5]])).reshape(-1,1))
B_pred

[[ 269]
 [ 220]
 [ 172]
 [ 132]
 [ 318]
 [ 367]
 [ 489]
 [ 636]
 [1144]
 [  38]
 [  40]
 [  92]
 [ 138]
 [  10]
 [  35]
 [  19]
 [  28]
 [  31]
 [ 120]
 [  30]
 [  33]
 [  61]
 [  76]
 [  23]
 [  69]
 [  33]
 [  27]
 [  77]
 [  27]
 [ 274]
 [ 368]
 [  32]
 [  63]
 [ 106]
 [ 208]
 [  20]
 [  29]
 [  71]
 [  26]
 [  36]
 [  40]
 [  52]
 [  60]
 [  72]
 [  72]
 [  18]
 [  20]
 [  40]
 [  62]
 [  24]
 [  24]
 [ 138]
 [  36]
 [  26]
 [  60]
 [  71]
 [  12]
 [  14]
 [  20]
 [  16]
 [  22]
 [  36]
 [ 144]
 [ 144]
 [ 259]
 [  17]
 [  26]
 [  32]
 [  32]
 [  62]
 [  64]
 [  22]
 [  36]
 [  44]
 [  50]
 [  45]
 [  53]
 [  36]
 [  84]
 [  16]
 [  38]
 [  38]
 [  16]
 [  22]
 [  29]
 [  40]
 [  35]
 [ 134]
 [  66]
 [ 141]
 [ 189]
 [  22]
 [ 132]
 [ 237]
 [ 465]
 [ 465]
 [ 277]
 [ 185]
 [   6]
 [  24]
 [  45]
 [   7]
 [  13]
 [  16]
 [  32]
 [  32]
 [  11]
 [  11]
 [  18]
 [  22]
 [  37]
 [  40]
 [  34]
 [  50]
 [  76]
 [  66]
 [  24]
 [  49]
 [  66]
 [ 100]
 [ 133]
 [  12]
 [  18]
 [  20]
 [  27]


C:\Users\cactu\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[33.12930511]])

In [30]:
#Mean absolute error
from sklearn.metrics import mean_absolute_error
mean_absolute_error(A, B_pred)

33.55440741263391

In [31]:
#Mean Square error
from sklearn.metrics import mean_squared_error
mean_squared_error(A, B_pred)

1125.8982568130214